version: "3.9"

services:
  database:
    container_name: skuddbot_v2_database
    build: database
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - net
    env_file: configs/.env
    restart: unless-stopped
  bot:
    build: .
    container_name: skuddbot_v2
    depends_on:
      - database
    networks:
      - net
    env_file:
      - configs/.env
      - configs/git.env
      - configs/global.env
    environment:
      - MYSQL_HOST=skuddbot_v2_database
    restart: unless-stopped


volumes:
  database:

networks:
  net: